<robot name="new_car" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="PI" value="3.14" />

    <material name="black">

        <color rgba="0.0 0.0 0.0 1.0" />

    </material>

    <material name="yellow">

        <color rgba="0.5 0.3 0.0 0.5" />

    </material>

    <xacro:property name="base_footprint_radius" value="0.001" />
    <xacro:property name="base_link_radius" value="0.1" />
    <xacro:property name="base_link_length" value="0.08" />
    <xacro:property name="earth_space" value="0.015" />

    <!-- 底盘 -->
    <link name="base_footprint">

        <visual>

            <geometry>

                <sphere radius="${base_footprint_radius}" />

            </geometry>

        </visual>

    </link>

    <link name="base_link">

        <visual>

            <geometry>

                <cylinder radius="${base_link_radius}" length="${base_link_length}" />

            </geometry>

            <origin xyz="0 0 0" />

            <material name="yellow" />

        </visual>

    </link>

    <joint name="base_link2base_footprint" type="fixed">

        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${earth_space + base_link_length / 2}" />

    </joint>

    <!-- 驱动轮 -->
    <xacro:property name="wheel_radius" value="0.0325" />
    <xacro:property name="wheel_length" value="0.015" />

    <xacro:macro name="add_wheels" params="name flag">

        <link name="${name}_wheel">

            <visual>

                <geometry>

                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />

                </geometry>

                <material name="black" />
                <origin xyz="0 0 0" rpy="${PI / 2} 0 0" />

            </visual>

        </link>

        <joint name="${name}_wheel2base_link" type="continuous">

            <parent link="base_link" />
            <child link="${name}_wheel" />

            <origin xyz="0 ${flag * base_link_radius} ${-(earth_space + base_link_length / 2 - wheel_radius)}" />
            <axis xyz="0 1 0" />

        </joint>

    </xacro:macro>

    <xacro:add_wheels name="left" flag="1" />
    <xacro:add_wheels name="right" flag="-1" />

    <!-- 万向轮 -->
    <xacro:property name="support_wheel_radius" value="0.0075" />

    <xacro:macro name="add_support_wheels" params="name flag">

        <link name="${name}_support_wheel">

            <visual>

                <geometry>

                    <sphere radius="${support_wheel_radius}" />

                </geometry>

                <material name="black" />

            </visual>

        </link>

        <joint name="${name}_support_wheel2base_link" type="continuous">

            <parent link="base_link" />
            <child link="${name}_support_wheel" />

            <origin xyz="${flag * (base_link_radius - support_wheel_radius)} 0 ${-(base_link_length / 2 + earth_space / 2)}" />
            <axis xyz="1 1 1" />

        </joint>

    </xacro:macro>

    <xacro:add_support_wheels name="front" flag="1" />
    <xacro:add_support_wheels name="back" flag="-1" />


</robot>